common_config_filepath: /Users/bennett/Code/ipl-playlist/configs/common.example.yml
items:
 - title: Hyun vs Major
   series: IPL Fight Club
   filepaths:
    - /Users/bennett/Code/ipl-playlist/assets/hyun_major_1.flv

 - title: Complexity vs Team ALT
   series: IPTL Amateur Season 1
   filepaths:
    - /Users/bennett/Code/ipl-playlist/assets/col_alt_1.flv
    - /Users/bennett/Code/ipl-playlist/assets/col_alt_2.flv